
project:
  type: website

website:
  title: "Drishti Gandhi"
  navbar:
    left:
      - text: "home"
        href: index.qmd
      - text: "about drishti"
        href: about.qmd
    right:
      - icon: github
        href: "https://github.com/Drishti16G/Drishti16G.github.io"
  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: false
  cache: false

editor: visual